### PR TITLE
Add support for XCommon CMake

### PR DESCRIPTION
**Pull request by danielpieczko**
Not sure if we want this in the changelog or not? For some very simple libraries, it will be the only change when next released.

### CODE REVIEW

**Comment by xross** [comment]
> Not sure if we want this in the changelog or not? For some very simple libraries, it will be the only change when next released.

I think it should be logged.

**Review by xross — CHANGES_REQUESTED** [review]
Changelog update shouldn't be under v6.0.0

**Comment by danielpieczko** [comment]
> Changelog update shouldn't be under v6.0.0

Can it be included in v6.0.0 because the release is only beta so far?

**Comment by xross** [comment]
> > Changelog update shouldn't be under v6.0.0
> 
> Can it be included in v6.0.0 because the release is only beta so far?

Id prefer it just to be a quality tag, just because we've never included changes between quality tags in changelogs before.

**Pull request merged**
